### ISSUE TITLE
It is possible to check for  port forward?

### ISSUE THREAD

**Issue by Klairm** [EHF32/livebox-api#1]
It is possible to check the NAT/PAP/CGNAT rules checking the name and external port?

**Comment by Klairm** [comment]
Because for example trying to display info of NAT I get this
![imagen](https://user-images.githubusercontent.com/40839469/174460191-c9d04d76-9674-451b-95a1-85f46e89c471.png)

**Comment by EHF32** [comment]
Hey,
You should request one of the [following parameters](https://github.com/EHF32/livebox-api/blob/140d37b1838e7570af0c9e4e9eea679096cdb9ed/parameter%20list/nat.md) in a post request as seen in [this](https://github.com/EHF32/livebox-api#example-read-wifi-status-and-other-options) example.

**Comment by Klairm** [comment]
> Hey, You should request one of the [following parameters](https://github.com/EHF32/livebox-api/blob/140d37b1838e7570af0c9e4e9eea679096cdb9ed/parameter%20list/nat.md) in a post request as seen in [this](https://github.com/EHF32/livebox-api#example-read-wifi-status-and-other-options) example.

but how do I send the parameter ?

**Comment by EHF32** [comment]
In the body as application/json array including the parameters you want to get.
Example curl to check if nat is enabled, the ip, local port and wan port of the first nat entry:
`curl --request GET -s --url http://localhost:3000/api/v1/nat  --header 'Content-Type: application/json'  --data '[ "Nat_enable", "lan_ipaddr1", "lan_port1", "wan_port1" ]'`

Gives the following output
![image](https://user-images.githubusercontent.com/46247068/176947012-652fbea6-6add-4367-949d-eff3210b5ff0.png)

**Comment by Klairm** [comment]
> In the body as application/json array including the parameters you want to get. Example curl to check if nat is enabled, the ip, local port and wan port of the first nat entry: `curl --request GET -s --url http://localhost:3000/api/v1/nat --header 'Content-Type: application/json' --data '[ "Nat_enable", "lan_ipaddr1", "lan_port1", "wan_port1" ]'`
> 
> Gives the following output ![image](https://user-images.githubusercontent.com/46247068/176947012-652fbea6-6add-4367-949d-eff3210b5ff0.png)

Ohh okay now I have it more clear thanks a lot for the example
